# Câu hỏi tự luận

## 1. Viết class và cài phương thức softmax

In [2]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

In [8]:
import warnings
warnings.filterwarnings("ignore")

In [14]:
import torch
import torch.nn as nn

class Softmax(nn.Module):
    def __init__(self):
        super(Softmax, self).__init__()

    def forward(self, x):
        exp_x = torch.exp(x)
        sum_exp_x = exp_x.sum(dim=0)
        return exp_x / sum_exp_x

data = torch.Tensor([1,2,3])
softmax = Softmax()
output = softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [16]:
data = torch.Tensor([1, 2, 3])


class softmax_stable(nn.Module):
    def __init__(self):
        super(softmax_stable, self).__init__()

    def forward(self, x):
        c = torch.max(x)
        exp_x = torch.exp(x - c)
        sum_exp_x = exp_x.sum(dim=0)
        return exp_x / sum_exp_x


softmax_stable = softmax_stable()
output = softmax_stable(data)
output

tensor([0.0900, 0.2447, 0.6652])

## 2 Ward

In [22]:
class Person:
    def __init__(self, name, yob):
        self.name = name
        self.yob = yob

    def describe(self):
        pass

class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.grade = grade

    def describe(self):
        return f"Student - Name: {self.name} - YoB: {self.yob} - Grade: {self.grade}"

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.subject = subject

    def describe(self):
        return f"Teacher - Name: {self.name} - YoB: {self.yob} - Subject: {self.subject}"

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self.specialist = specialist

    def describe(self):
        return f"Doctor - Name: {self.name} - YoB: {self.yob} - Specialist: {self.specialist}"


In [40]:
class Ward:
    def __init__(self, name):
        self.name =name
        self.people =[]

    def add_person(self, person):
        self.people.append(person)

    def describe(self):
        print(f"Ward: {self.name}")
        for person in self.people:
            print(person.describe())

    def count_doctor(self):
        return sum(1 for person in self.people if isinstance(person, Doctor))

    def sort_age(self):
        self.people.sort(key=lambda person: person.yob, reverse = True)


    def compute_average(self):
        teachers = [person for person in self.people if isinstance(person, Teacher)]
        if not teachers:
            return 0
        return sum(teacher.yob for teacher in teachers) / len(teachers)


In [41]:
student1 = Student ( name =" studentA ", yob =2010 , grade ="7")
student1.describe()

'Student - Name:  studentA  - YoB: 2010 - Grade: 7'

In [42]:
teacher1 = Teacher ( name =" teacherA ", yob =1969 , subject =" Math ")
teacher1 . describe ()

'Teacher - Name:  teacherA  - YoB: 1969 - Subject:  Math '

In [43]:
doctor1 = Doctor ( name =" doctorA ", yob =1945 , specialist =" Endocrinologists ")
doctor1.describe ()

'Doctor - Name:  doctorA  - YoB: 1945 - Specialist:  Endocrinologists '

In [44]:
print ()
teacher2 = Teacher ( name ="teacherB ", yob =1995 , subject ="History ")
doctor2 = Doctor ( name ="doctorB ", yob =1975 , specialist ="Cardiologists ")
ward1 = Ward ( name ="Ward1 ")
ward1.add_person ( student1 )
ward1.add_person ( teacher1 )
ward1.add_person ( teacher2 )
ward1.add_person ( doctor1 )
ward1.add_person ( doctor2 )
ward1.describe ()


Ward: Ward1 
Student - Name:  studentA  - YoB: 2010 - Grade: 7
Teacher - Name:  teacherA  - YoB: 1969 - Subject:  Math 
Teacher - Name: teacherB  - YoB: 1995 - Subject: History 
Doctor - Name:  doctorA  - YoB: 1945 - Specialist:  Endocrinologists 
Doctor - Name: doctorB  - YoB: 1975 - Specialist: Cardiologists 


In [45]:
print ( f"\nNumber of doctors : { ward1.count_doctor()}")


Number of doctors : 2


In [46]:
print ("\nAfter sorting Age of Ward1 people ")
ward1.sort_age()
ward1.describe()


After sorting Age of Ward1 people 
Ward: Ward1 
Student - Name:  studentA  - YoB: 2010 - Grade: 7
Teacher - Name: teacherB  - YoB: 1995 - Subject: History 
Doctor - Name: doctorB  - YoB: 1975 - Specialist: Cardiologists 
Teacher - Name:  teacherA  - YoB: 1969 - Subject:  Math 
Doctor - Name:  doctorA  - YoB: 1945 - Specialist:  Endocrinologists 


In [47]:
print( f"\nAverage year of birth ( teachers ): { ward1.compute_average ()}")


Average year of birth ( teachers ): 1982.0


## 3

In [49]:
class Stack:
    def __init__(self, capacity):
        self.capacity = capacity
        self.stack = []

    def is_empty(self):
        return len(self.stack) == 0

    def is_full(self):
        return len(self.stack) == self.capacity

    def pop(self):
        if self.is_empty():
            raise IndexError("Pop from an empty stack")
        return self.stack.pop()

    def push(self, value):
        if self.is_full():
            raise OverflowError("Push to a full stack")
        self.stack.append(value)

    def top(self):
        if self.is_empty():
            raise IndexError("Top from an empty stack")
        return self.stack[-1]

In [50]:
stack1 = Stack(capacity=5)

stack1.push(1)
stack1.push(2)

print(stack1.is_full())

print(stack1.top())

print(stack1.pop())

print(stack1.top())

print(stack1.pop())

print(stack1.is_empty())


False
2
2
1
1
True


## 4.

In [51]:
class Queue:
    def __init__(self, capacity):
        self.capacity = capacity
        self.queue = []

    def is_empty(self):
        return len(self.queue) == 0

    def is_full(self):
        return len(self.queue) == self.capacity

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Dequeue from an empty queue")
        return self.queue.pop(0)

    def enqueue(self, value):
        if self.is_full():
            raise OverflowError("Enqueue to a full queue")
        self.queue.append(value)

    def front(self):
        if self.is_empty():
            raise IndexError("Front from an empty queue")
        return self.queue[0]

In [53]:
queue1 = Queue(capacity = 5)
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1.is_full())
print(queue1.front())
print(queue1.dequeue())
print(queue1.front())
print(queue1.dequeue())
print(queue1.is_empty())

False
1
1
2
2
True


# Câu hỏi trắc nghiệm

## 1

Câu hỏi 1: Kết quả của đoạn code dưới đây là bao nhiêu.

In [54]:
import torch
import torch.nn as nn


data = torch.Tensor([1,2,3])
softmax = nn.Softmax()
output = softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [55]:
assert round(output[0].item(), 2) == 0.09

## 2.
Câu hỏi 2: Hoàn thành đoạn code sau đây theo công thức tính softmax.

In [56]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        exp_x = torch.exp(x)
        sum_exp_x = exp_x.sum(dim=0)
        return exp_x / sum_exp_x

In [57]:
data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[-1].item(), 2) == 0.26

In [58]:
output

tensor([0.7054, 0.0351, 0.2595])

## 3.
Câu hỏi 3: Hoàn thành đoạn code sau đây theo công thức tính softmax.

In [59]:
data = torch.Tensor([1,2,300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round ( output [0]. item () , 2) == 0.0

In [60]:
output

tensor([0., 0., nan])

## 4.
Câu hỏi 4: Hoàn thành đoạn code sau đây theo công thức tính stable softmax.

In [61]:
class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim = 0, keepdims = True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition

data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67

In [62]:
output

tensor([0.0900, 0.2447, 0.6652])

## 5.
Một người (person) có thể là student, doctor, hoặc teacher. Một student gồm có name
(string), yob (int) (năm sinh), và grade (string). Các bạn thực hiện viết class Student theo mô tả
trên (Các bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả
đầu ra là gì? Chọn đáp án đúng nhất bên dưới.

In [65]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: str):
        super().__init__(name, yob)
        self._grade = grade

    def describe(self):
        return f"Student - Name: {self._name} - YoB: {self._yob} - Grade: {self._grade}"

student1 = Student ( name =" studentZ2023 ", yob =2011 , grade ="6")
assert student1._yob == 2011

In [66]:
student1.describe()

'Student - Name:  studentZ2023  - YoB: 2011 - Grade: 6'

## 6.
Câu hỏi 6: Một người (person) có thể là student, doctor, hoặc teacher. Một teacher gồm có name
(string), yob (int), và subject (string). Các bạn thực hiện viết class Teacher theo mô tả trên (Các
bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả đầu ra là
gì? Chọn đáp án đúng nhất bên dưới.

In [67]:
class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str):
        super().__init__(name, yob)
        self._subject = subject

    def describe(self):
        return f"Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self._subject}"

In [68]:
teacher1 = Teacher ( name ="teacherZ2023 ", yob =1991 , subject ="History ")
assert teacher1._yob == 1991

In [69]:
teacher1 . describe ()

'Teacher - Name: teacherZ2023  - YoB: 1991 - Subject: History '

## 7.
Câu hỏi 7: Một người (person) có thể là student, doctor, hoặc teacher. Một doctor gồm có name
(string), yob (string), và specialist (string). Các bạn thực hiện viết class Teacher theo mô tả trên
(Các bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả đầu
ra là gì? Chọn đáp án đúng nhất bên dưới.

In [70]:
class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: str):
        super().__init__(name, yob)
        self._specialist = specialist

    def describe(self):
        return f"Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self._specialist}"

In [71]:
doctor1 = Doctor ( name ="doctorZ2023 ", yob =1981 , specialist ="Endocrinologists ")
assert doctor1._yob == 1981

In [72]:
doctor1.describe()

'Doctor - Name: doctorZ2023  - YoB: 1981 - Specialist: Endocrinologists '

## 8.
Câu hỏi 8 Một Ward gồm có name (string) và danh sách của mọi người trong Ward. Một người
person có thể là student, doctor, hoặc teacher và cần sử dụng một list để chứa danh sách của mọi
người trong Ward. Viết add_person(person) method trong Ward class để add thêm một người
mới với nghề nghiệp bất kỳ (student, teacher, doctor) vào danh sách người của ward. Tạo ra một
ward object, và thêm vào 1 student, 2 teacher, và 2 doctor. Thực hiện describe() method để in ra
tên ward (name) và toàn bộ thông tin của từng người trong ward. Chọn đáp án đúng nhất bên
dưới cho phương thức đếm số lượng doctor.

In [73]:
class Ward:
    def __init__(self, name: str):
        self.__name = name
        self.__listPeople = list()

    def add_person(self, person: Person):
        self.__listPeople.append(person)

    def describe(self):
        print(f"Ward Name: {self.__name}")
        for p in self.__listPeople:
            print(p.describe())

    def count_doctor(self):
        return sum(1 for p in self.__listPeople if isinstance(p, Doctor))



In [75]:
student1 = Student(name="studentA", yob=2010, grade="7")
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")

doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")


ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

ward1.count_doctor()


2

##9.
Câu hỏi 9 Thực hiện xây dựng class Stack với các chức năng (method) sau đây: initial- ization
method nhận một input "capacity": dùng để khởi tạo stack với capacity là số lượng element mà
stack có thể chứa. .is_full(): kiểm tra stack đã full chưa. .push(value) add thêm value vào trong
stack. Kết quả đầu ra là gì?

In [76]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if self.is_full():
            raise OverflowError("Stack is full")
        self.__stack.append(value)

In [78]:
stack1 = MyStack ( capacity =5)
stack1.push(1)

In [79]:
assert stack1.is_full() == False

In [80]:
stack1.push(2)
print(stack1.is_full())

False


## 10.

Câu hỏi 10: Thực hiện xây dựng class Stack với các chức năng (method) sau đây: initialization
method nhận một input "capacity", dùng để khởi tạo stack với capacity là số lượng element mà
stack có thể chứa. Phương thức is_empty(): kiểm tra stack có đang rỗng. Phương thức is_full():
kiểm tra stack đã full chưa. Phương thức push(value) add thêm value vào trong stack. Phương
thức top() lấy giá trị top element hiện tại của stack, nhưng không loại bỏ giá trị đó. Kết quả đầu
ra là gì?

In [82]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if self.is_full():
            raise OverflowError("Stack is full")
        self.__stack.append(value)

    def top(self):
        if not self.__stack:
            raise IndexError("Stack is empty")
        return self.__stack[-1]


In [83]:
stack1 = MyStack ( capacity =5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print ( stack1.top() )

1


## 11.
Câu hỏi 11: Thực hiện xây dựng class Queue với các chức năng (method) sau đây: initialization
method nhận một input "capacity", dùng để khởi tạo queue với capacity là số lượng element mà
queue có thể chứa. Phương thức is_full(): kiểm tra queue đã full chưa. Phương thức enqueue(value)
add thêm value vào trong queue. Kết quả đầu ra là gì?

In [86]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        if self.is_full():
            raise OverflowError("Queue is full")
        self.__queue.append(value)

queue1 = MyQueue(capacity=5)
queue1.enqueue(1)

assert queue1.is_full() == False

In [87]:
queue1.enqueue(2)
print(queue1.is_full())

False


## 12.
Câu hỏi 12: Thực hiện xây dựng class Queue với các chức năng (method) sau đây: initialization
method nhận một input "capacity" dùng để khởi tạo queue với capacity là số lượng element mà
queue có thể chứa. Phương thức is_full(): kiểm tra queue đã full chưa. Phương thức enqueue(value)
add thêm value vào trong queue. Phương thức front() lấy giá trị first element hiện tại của queue,
nhưng không loại bỏ giá trị đó. Kết quả đầu ra là gì?

In [88]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def isEmpty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        if self.is_full():
            raise OverflowError("Queue is full")
        self.__queue.append(value)

    def dequeue(self):
        if self.isEmpty():
            raise IndexError("Queue is empty")
        return self.__queue.pop(0)

    def front(self):
        if self.isEmpty():
            raise IndexError("Queue is empty")
        return self.__queue[0]

queue1 = MyQueue(capacity=5)
queue1.enqueue(1)

assert queue1.is_full() == False

In [89]:
queue1.enqueue(2)
print(queue1.front())

1
